### PR TITLE
Start updating for mupdf 1.19

### PR DESCRIPTION
**Pull request by ivanholmes**
As part of my project to get the latest version of MuPDF into HaikuPorts https://github.com/haikuports/haikuports/pull/6823 I have updated applications that depend on it https://github.com/threedeyes/PDFTranslator/pull/5 leaving only this one to update as far as I know. 

I have updated all the function calls to suit the new version of the library, but I've run into issues with the multi-threaded loading where for some files it seems one of the threads doesn't release `fRendermutex` and the program hangs. EDIT - think I fixed this by initialising the mutex. Not sure if this is the right thing to do (I haven't worked with threads before) 

There are other crashes too and functionality that doesn't work. 

Clearly I have missed something - I'm looking for advice on how to debug something like this and a second pair of eyes on my code. Any help would be much appreciated.

I will of course carry on working on this when I get a chance.

The code from this pull request doesn't work properly so isn't ready to merge!

### CODE REVIEW

**Comment by waddlesplash** [comment]
1. Indent using tabs not spaces.
2. Remove dead/unneeded code, don't comment it out.

DocumentViewer often crashes in PDF mode as it is so that may not even be a regression.

The mutex does need to be initialized, strange it wasn't done before. That may fix some of the crashes indeed...

**Comment by ivanholmes** [comment]
> 1. Indent using tabs not spaces.
> 2. Remove dead/unneeded code, don't comment it out.

No problem, when the PR is ready to merge I'll make sure these are done.

> DocumentViewer often crashes in PDF mode as it is so that may not even be a regression.
> 
> The mutex does need to be initialized, strange it wasn't done before. That may fix some of the crashes indeed...

It does, it gets further at least but then some PDF files cause other errors. These same files open fine with the version in HaikuDepot. I will keep working on it, at least to get the PDFs I have to load properly.

Thanks for the help!

**Comment by ivanholmes** [comment]
The latest commit brings it back up to parity with the existing version I believe. Some files still can't be opened but this seems to be because they contain errors that MuPDF won't tolerate rather than because of any code in DocumentViewer itself.

I've also converted PDFEngine.cpp to use tabs rather than spaces for indenting and removed the dead code I had commented. I left the previous dead code in place but I could remove it if you feel that is better.

From my point of view I would be happy to merge now but also happy to make any simple changes you feel would be beneficial.

**Comment by waddlesplash** [comment]
You may as well remove older dead code, yes.

**Comment by ivanholmes** [comment]
> You may as well remove older dead code, yes.

Okay, I'll do this when I get the change and then push, cheers

**Comment by waddlesplash** [comment]
Ready for merge?

**Comment by ivanholmes** [comment]
> Ready for merge?

Yes it is from my POV. When merged I'll update the recipe in Haikuports.

**Pull request merged**
